---
- name: Start deploy sites playbook...
  hosts: varnish
#  gather_facts: false
#  vars_files:
#    - vars/apache.yml

  tasks:
    - name: Include varnish vars...
      include_vars: vars/varnish.params.yml

    - name: Include site vars...
      include_vars: vars/sites.yml

    - name: Set varnish facts task...
      include: tasks/daemon_facts.yml

    - name: Include varnish config task...
      include: tasks/daemon.yml

    - name: Include sites config task...
      include: tasks/sites.yml
