---
- name: Start deploy sites playbook...
  hosts: varnish

  tasks:
    - name: Include varnish vars...
      include_vars: vars/varnish.params.yml

    - name: Include site vars...
      include_vars: vars/sites.yml

    - name: Include varnish config task...
      include: tasks/daemon.yml

    - name: Include sites config task...
      include: tasks/sites.yml

    - name: Started varnish service
      service:
        name: varnish
        state: started

    - name: Reload_varnish
      service:
        name: varnish
        state: reloaded
      when: varnish_conf.changed
