---
- name: Start deploy sites playbook...
  hosts: varnish

  tasks:
    - name: Include varnish vars...
      include_vars: vars/varnish.params.yml

    - name: Include site vars...
      include_vars: vars/sites.yml

    - name: Include varnish config task...
      include: tasks/daemon.yml

    - name: Include sites config task...
      include: tasks/sites.yml

    - name: Varnish service reloading... (skipping if config files don't change)
      service:
        name: varnish
        state: reloaded
      when: varnish_conf.changed

    - name: Varnish service starting/reloading...
      block:
        - name: Started varnish service...
          service:
            name: varnish
            state: started
        - name: Varnish service reloading... (skipping if config files don't change)
          service:
            name: varnish
            state: reloaded
          when: varnish_conf.changed
      rescue:
          - debug:
            msg: 'I caught an error, can do stuff here to fix it, :-)'
