---
- name: Add consul server config to the server...
  template:
    src: templates/server.conf.j2
    dest: /etc/consul.d/server.conf
    backup: yes

- name: Started consul...
  service:
    name: mysql
    state: started
