---
- name: Start PerconaServer playbook...
  hosts: dbservers

  tasks:
#    - name: Include defaults vars...
#      include_vars: vars/PerconaServer_variables.yml
    - name: Generate MySQL server-id
      shell: hostname -I | sed -e 's/ \+\([a-z0-9]\+\:\)\+[a-z0-9]\+//' | sed -e 's/ /\n/' | grep -v '^$' | tail -1 | awk -F. '{print $3 * 256 + $4}'
      register: mysql_server_id

    - name: Include defaults_origin vars...
      include: vars/defaults_origin.yml

    - name: Include PerconaServer vars...
      include_vars: vars/memory_table.yml

    - name: Installing PerconaServer...
      include: tasks/install.yml

    - name: Runing PerconaServer config task...
      include: tasks/configure.yml

    - name: Runing PerconaServer first config task...
      include: tasks/first_config.yml

    - name: Running create user task...
      include: tasks/create_user.yml

#  handlers:
#    - name: Reload afrer site change
#      debug:
#        var: hostvars[inventory_hostname]
