---
- name: Start PerconaServer playbook...
  hosts: dbservers

  tasks:
    - name: Include defaults_origin vars...
      include_vars: vars/defaults_origin.yml

    - name: Include PerconaServer vars...
      include_vars: vars/memory_table.yml

    - name: Installing PerconaServer...
      include: tasks/install.yml

    - name: Runing PerconaServer config task...
      include: tasks/configure.yml

    - name: Runing PerconaServer first config task...
      include: tasks/first_config.yml

#  handlers:
#    - name: Reload afrer site change
#      debug:
#        var: hostvars[inventory_hostname]
