---
- name: Start deploy sites playbook...
  hosts: varnish

  tasks:
    - name: Include varnish vars...
      include_vars: vars/varnish.params.yml

    - name: Include site vars...
      include_vars: vars/sites.yml

    - name: Include varnish config task...
      include: tasks/daemon.yml

    - name: Include sites config task...
      include: tasks/sites.yml

#  handlers:
#    - name: Reload afrer site change
#      debug:
#        var: hostvars[inventory_hostname]
    - name: (Re)started varnish service...
      block:
        - name: Started varnish service...
          service:
            name: varnish
            state: started
        - name: Varnish service reloading... (skipping if config files don't change)
          service:
            name: varnish
            state: reloaded
          when: varnish_conf.changed or varnish_srv.changed
        - name: Remove varnish.params backup (skipping if backup don't exist) 
          shell: rm -f "{{ varnish_srv.backup_file }}"
          when: varnish_srv.changed
        - name: Remove sites.vcl backup (skipping if backup don't exist)
          shell: rm -f "{{ varnish_conf.backup_file }}"
          when: varnish_conf.changed
      rescue:
        - name: Restore varnish.params... (skipping if config file don't change)
          command: mv -f "{{ varnish_srv.backup_file }}" /etc/varnish/varnish.params
          when: varnish_srv.changed
        - name: Restore sites.vcl... (skipping if config file don't change)
          command: mv -f "{{ varnish_conf.backup_file }}" /etc/varnish/sites.vcl
          when: varnish_conf.changed
        - name: Started varnish service...
          service:
            name: varnish
            state: started
        - name: Reloaded varnish service...
          service:
            name: varnish
            state: reloaded
