---
- name: Add varnish config to the server...
  template:
    src: templates/varnish.params.j2
    dest: /etc/varnish/varnish.params
  register: varnish_conf

- name: Enable service varnish, and not touch the state
  service:
    name: varnish
    enabled: yes
