---
- name: Add mysql config to the server...
  template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf
    backup: yes

- name: Create a directory if it does not exist
  file:
    path: "{{datadir}}"
    state: directory
    owner: mysql
    group: mysql
    mode: '0775'

- name: Create a directory if it does not exist
  file:
    path: "{{tmpdir}}"
    owner: mysql
    group: mysql
    state: directory
    mode: '0775'

- name: Started mysql server
  service:
    name: mysql
    state: started
