---
- name: Add mysql config to the server...
  template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf
    backup: yes

- name: Restarted mysql server after install
  service:
    name: mysql
    state: restarted
  when: first_install.changed
